/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class BlockAllocator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BlockAllocator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BlockAllocator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(BlockAllocator obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_BlockAllocator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BlockAllocator() {
    this(liquidfunJNI.new_BlockAllocator(), true);
  }

  public SWIGTYPE_p_void allocate(int size) {
    long cPtr = liquidfunJNI.BlockAllocator_allocate(swigCPtr, this, size);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void free(SWIGTYPE_p_void p, int size) {
    liquidfunJNI.BlockAllocator_free(swigCPtr, this, SWIGTYPE_p_void.getCPtr(p), size);
  }

  public void clear() {
    liquidfunJNI.BlockAllocator_clear(swigCPtr, this);
  }

  public long getNumGiantAllocations() {
    return liquidfunJNI.BlockAllocator_getNumGiantAllocations(swigCPtr, this);
  }

}
