/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class DestructionListener {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DestructionListener(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DestructionListener obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(DestructionListener obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_DestructionListener(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void sayGoodbye(Joint joint) {
    liquidfunJNI.DestructionListener_sayGoodbye__SWIG_0(swigCPtr, this, Joint.getCPtr(joint), joint);
  }

  public void sayGoodbye(Fixture fixture) {
    liquidfunJNI.DestructionListener_sayGoodbye__SWIG_1(swigCPtr, this, Fixture.getCPtr(fixture), fixture);
  }

  public void sayGoodbye(ParticleGroup group) {
    liquidfunJNI.DestructionListener_sayGoodbye__SWIG_2(swigCPtr, this, ParticleGroup.getCPtr(group), group);
  }

  public void sayGoodbye(ParticleSystem particleSystem, int index) {
    liquidfunJNI.DestructionListener_sayGoodbye__SWIG_3(swigCPtr, this, ParticleSystem.getCPtr(particleSystem), particleSystem, index);
  }

}
