/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class QueryCallback {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public QueryCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(QueryCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(QueryCallback obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_QueryCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean reportFixture(Fixture fixture) {
    return liquidfunJNI.QueryCallback_reportFixture(swigCPtr, this, Fixture.getCPtr(fixture), fixture);
  }

  public boolean reportParticle(ParticleSystem particleSystem, int index) {
    return liquidfunJNI.QueryCallback_reportParticle(swigCPtr, this, ParticleSystem.getCPtr(particleSystem), particleSystem, index);
  }

  public boolean shouldQueryParticleSystem(ParticleSystem particleSystem) {
    return liquidfunJNI.QueryCallback_shouldQueryParticleSystem(swigCPtr, this, ParticleSystem.getCPtr(particleSystem), particleSystem);
  }

}
