/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class StackAllocator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StackAllocator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StackAllocator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(StackAllocator obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_StackAllocator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public StackAllocator() {
    this(liquidfunJNI.new_StackAllocator(), true);
  }

  public SWIGTYPE_p_void allocate(int size) {
    long cPtr = liquidfunJNI.StackAllocator_allocate(swigCPtr, this, size);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public SWIGTYPE_p_void reallocate(SWIGTYPE_p_void p, int size) {
    long cPtr = liquidfunJNI.StackAllocator_reallocate(swigCPtr, this, SWIGTYPE_p_void.getCPtr(p), size);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void free(SWIGTYPE_p_void p) {
    liquidfunJNI.StackAllocator_free(swigCPtr, this, SWIGTYPE_p_void.getCPtr(p));
  }

  public int getMaxAllocation() {
    return liquidfunJNI.StackAllocator_getMaxAllocation(swigCPtr, this);
  }

  public final static int MIN_ALIGNMENT = liquidfunJNI.StackAllocator_MIN_ALIGNMENT_get();

  public final static int ALIGN_MASK = liquidfunJNI.StackAllocator_ALIGN_MASK_get();

}
